[build]
    publish="build"
    [context.production]
        publish="build"
        command="npm run build"
        environment= { GITHUB_CLIENT_ID = "1f9e615270f38581da43", GITHUB_CLIENT_SECRET="f0f6e83da620f7cefb727ada469861fd492460c2", NODE_ENV="production" }